//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqualCreekBusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public string EventTitle { get; set; }
        public string EventDescription { get; set; }
        public string BookedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
