//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqualCreekBusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeeTime
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> ScheduleTime { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string BookedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> NumberOfPlayers { get; set; }
        public Nullable<bool> Member { get; set; }
        public Nullable<bool> Cart { get; set; }
    }
}
